### PR TITLE
Adding some best-practice headers to all requests for security hardening

### PR DESCRIPTION
**Pull request by nnieslan**

### CODE REVIEW

**Comment by nnieslan** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;0Zyb0vdt&#x2F;694-salesforce-fix-api-security-scanning-bugs"> Salesforce - Fix API Security Scanning bugs!</a>

**Comment by bensperr** [comment]
Hmm... This brings up whether we want to continue supporting our forked copy rather than the real copy. I don't think we actually need our copy anymore - the bug was fixed. It would be nice not to have to rebuild and redeploy for every change to this conf. What's the effort involved in doing this as a regular extended conf?

**Comment by nnieslan** [comment]
Good question - Since the addheader statements are global, rather than vhost specific, I'd need to see if I can volume map an nginx include conf file into the container that already has automatic inclusion outside of a server {} block

**Comment by nnieslan** [comment]
Oh now that i look at it, I can do it.  I know how.  I'll make the change to use a conf include.  geez.  good call.

**Pull request closed without merging**
